services:
  # Backend API service
  api:
    build: ./server
    container_name: socket-api
    ports:
      - "4000:4000"
    # Sync host files with container for hot-reloading
    volumes:
      - ./server:/usr/src/app
      # Prevents host node_modules from overwriting container node_modules
      - /usr/src/app/node_modules
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development