version: "3.9"

services:
  # Backend API service
  api:
    build: ./server
    container_name: socket-api
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
    command: npm run dev   # nodemon

  # Frontend service (Vite)
  frontend:
    build: ./client
    container_name: socket-frontend
    ports:
      - "5173:5173"      # Vite default dev server port
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
